---
title: "acute chronic"
author: "Cynthia Xiao"
date: "November 7, 2018"
output: html_document
---

```{r pre-job}
soccer <- read.csv("C:/Users/shuyuex2/Desktop/Soccer FA18/example (1).csv", header = T)
name <- levels(soccer$Name)

#AC <-0
begin <- as.Date("2018-07-31")
end <- as.Date("2018-10-30")
soccer$qtest <- as.Date(soccer$qtest,"%m/%d/%Y")

############################
#test if date is continuous#
############################
library(lubridate)
NPD <- matrix(0,as.numeric(end-begin+1),2)
NPD <- as.data.frame(NPD)
names(NPD) <- c("qtest","number")
NPD$qtest<- begin


for (i in 1:nrow(NPD)) {
  NPD$qtest[i] <- begin+i-1
  NPD$number[i]<- length(unique(soccer$Name[which(soccer$qtest==NPD$qtest[i])]))
}

lostday <- NPD$qtest[which(NPD$number!=30)]
NPD$lostname <- 0
for (i in 1:length(lostday)) {
  print(lostday[i])
  print(setdiff(name,unique(soccer$Name[which(soccer$qtest==lostday[i])])))
}


```

acute/chronic ratio
```{r add columns}
##########
#7/28 AC:#
##########
AC <-0
for (i in 1:length(name)) {
  soccer_part <- soccer[which(soccer$Name==name[i]),]
  soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = FALSE),]
  soccer_part$A.C <- 0
  n <- nrow(soccer_part)
 
  for (j in 1:n) {
    if(soccer_part$qtest[j] <= begin+28)next
    else{
      date_length28 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-28))
      date_length7 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-7))
      soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length7):(j-1)])/mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #print(date_length7)
      #soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = TRUE),]
    } 
  }
  AC <- c(AC,soccer_part$A.C)
  
}

soccer$AC_7_28 <- AC[-1]



##########
#4/28 AC:#
##########
AC <-0
for (i in 1:length(name)) {
  soccer_part <- soccer[which(soccer$Name==name[i]),]
  soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = FALSE),]
  soccer_part$A.C <- 0
  n <- nrow(soccer_part)
  
  for (j in 1:n) {
    if(soccer_part$qtest[j] <= begin+28)next
    else{
      date_length28 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-28))
      date_length4 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-4))
      soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length4):(j-1)])/mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #print(date_length7)
    } 
  }
  AC <- c(AC,soccer_part$A.C)
  
}

soccer$AC_4_28 <- AC[-1]


##########
#3/28 AC:#
##########
AC <-0
for (i in 1:length(name)) {
  soccer_part <- soccer[which(soccer$Name==name[i]),]
  soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = FALSE),]
  soccer_part$A.C <- 0
  n <- nrow(soccer_part)
  
  for (j in 1:n) {
    if(soccer_part$qtest[j] <= begin+28)next
    else{
      date_length28 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-28))
      date_length3 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-3))
      soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length3):(j-1)])/mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #print(date_length7)
    } 
  }
  AC <- c(AC,soccer_part$A.C)
  
}

soccer$AC_3_28 <- AC[-1]


##########
#4/14 AC:#
##########
AC <-0
for (i in 1:length(name)) {
  
  soccer_part <- soccer[which(soccer$Name==name[i]),]
  soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = FALSE),]
  soccer_part$A.C <- 0
  n <- nrow(soccer_part)
  
  for (j in 1:n) {
    if(soccer_part$qtest[j] <= begin+14)next
    else{
      date_length14 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-14))
      date_length4 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-4))
      soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length4):(j-1)])/mean(soccer_part$Training.load.score[(j-date_length14):(j-1)])
      #soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #print(date_length7)
    } 
  }
  AC <- c(AC,soccer_part$A.C)
  
}

soccer$AC_4_14 <- AC[-1]

write.csv(soccer,"C:/Users/shuyuex2/Desktop/Soccer FA18/Soccer-A.C.csv")

```

injure
```{r injury}
Survey <- read.csv("C:/Users/shuyuex2/Desktop/Soccer FA18/Surveys.csv", header = T)
#Survey <- Survey[,c("Name","qtest","Injuries")]
soccerAC <- read.csv("C:/Users/shuyuex2/Desktop/Soccer FA18/Soccer-A.C.csv", header = T)
#soccerAC <- soccerAC[order(soccerAC$qtest, decreasing = FALSE),]
soccerAC$qtest <- as.Date(soccerAC$qtest)
soccerAC$injure <- "No"
Survey$Injuries <- as.character(Survey$Injuries)

for (i in 1:nrow(soccerAC)) {
  date <- as.character(soccerAC$qtest[i])
  name <- as.character(soccerAC$Name[i])
  if(dim(Survey[Survey$Name==name && Survey$qtest==date,])[1]==0)next
  else {soccerAC$injure[i] <- "Yes"}
}

for (i in 1:nrow(Survey)) {
  if(Survey$Injuries[i]=="No")next
  else {
    date <- as.character(Survey$qtest[i])
    name <- as.character(Survey$Name[i])
    soccerAC$injure[which(soccerAC$Name==name & soccerAC$qtest==date)] <- "Yes"
  }
}

write.csv(soccerAC,"C:/Users/shuyuex2/Desktop/Soccer FA18/SoccerALL.csv")


```

```{r 1}
#average when get injuried
#average when not get injuried
#average overall

#7/28
mean(soccerAC$AC_7_28[which(soccerAC$AC_7_28!=0 & soccerAC$injure=="Yes")])
mean(soccerAC$AC_7_28[which(soccerAC$AC_7_28!=0 & soccerAC$injure=="No")])
mean(soccerAC$AC_7_28[which(soccerAC$AC_7_28!=0)])
#soccerAC$meanAC_4_28 <- mean()

#4/28
mean(soccerAC$AC_4_28[which(soccerAC$AC_4_28!=0 & soccerAC$injure=="Yes")])
mean(soccerAC$AC_4_28[which(soccerAC$AC_4_28!=0 & soccerAC$injure=="No")])
mean(soccerAC$AC_4_28[which(soccerAC$AC_4_28!=0)])
#3/28
mean(soccerAC$AC_3_28[which(soccerAC$AC_3_28!=0 & soccerAC$injure=="Yes")])
mean(soccerAC$AC_3_28[which(soccerAC$AC_3_28!=0 & soccerAC$injure=="No")])
mean(soccerAC$AC_3_28[which(soccerAC$AC_3_28!=0)])
#4/14
mean(soccerAC$AC_4_14[which(soccerAC$AC_4_14!=0 & soccerAC$injure=="Yes")])
mean(soccerAC$AC_4_14[which(soccerAC$AC_4_14!=0 & soccerAC$injure=="No")])
mean(soccerAC$AC_4_14[which(soccerAC$AC_4_14!=0)])
```

4/28 mean
```{r}

#4/28 mean
meanAC <-0

name <- levels(soccerAC$Name)
for (i in 1:length(name)) {
  soccer_part <- soccer[which(soccer$Name==name[i]),]
  soccer_part <- soccer_part[order(soccer_part$qtest, decreasing = FALSE),]
  soccer_part$meanAC <- 0
  n <- nrow(soccer_part)
  
  for (j in 1:n) {
    if(soccer_part$qtest[j] <= begin+28) a <- j
    else{
      #date_length28 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-28))
      #date_length4 <- max(which(soccer_part$qtest==soccer_part$qtest[j]-1))-min(which(soccer_part$qtest==soccer_part$qtest[j]-4))
      soccer_part$meanAC[j] <- mean(soccer_part$AC_4_28[(a+1):j])
      #soccer_part$A.C[j] <- mean(soccer_part$Training.load.score[(j-date_length28):(j-1)])
      #print(date_length7)
    } 
  }
  meanAC <- c(meanAC,soccer_part$meanAC)
  
}

soccerAC$meanAC_4_28 <- meanAC[-1]
write.csv(soccerAC,"C:/Users/shuyuex2/Desktop/Soccer FA18/soccerALL.csv")



```


```{r id-sd}
#7/28 sd:
individual_sd <- matrix(0,length(name),5)
individual_sd <- as.data.frame(individual_sd)
names(individual_sd)<- c("name","sd_7_28","sd_4_28","sd_3_28","sd_4_14")
name <- levels(soccer$Name)
for (i in 1:length(name)) {
  individual_sd$name[i] <- name[i]
  individual_sd$sd_7_28[i] <- sd(soccerAC$AC_7_28[which(soccerAC$AC_7_28!=0 & soccerAC$Name==name[i])])
  individual_sd$sd_4_28[i] <- sd(soccerAC$AC_4_28[which(soccerAC$AC_4_28!=0 & soccerAC$Name==name[i])])
  individual_sd$sd_3_28[i] <- sd(soccerAC$AC_3_28[which(soccerAC$AC_3_28!=0 & soccerAC$Name==name[i])])
  individual_sd$sd_4_14[i] <- sd(soccerAC$AC_4_14[which(soccerAC$AC_4_14!=0 & soccerAC$Name==name[i])])
  
}


```


